name: Publish Docker
on: 
  push:
    branches:
      - master
      - dev
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        ELASTICSEARCH_VERSION: 7.8.1
        JIEBAPLUGIN_VERSION: 7.8.1
      with:
        name: ${{ secrets.DOCKERHUB_IMAGENAME }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        buildargs: ELASTICSEARCH_VERSION,JIEBAPLUGIN_VERSION
